app:
  eureka:
    user: admin
    pass: admin
    host: localhost
    port: 8761

eureka:
  client:
    service-url:
      defaultZone: http://${app.eureka.user}:${app.eureka.pass}@${app.eureka.host}:${app.eureka.port}/eureka/
    register-with-eureka: true
    fetch-registry: true
    instance:
      prefer-ip-address: true
      hostname: localhost

management:
  info.git:
    mode: full
    enabled: true
  endpoints:
    web:
      exposure.include: "*"
  endpoint:
    health:
      show-details: always
      enabled: true
      access: public
    shutdown:
      access: public
      enabled: true
    metrics:
      access: public
      enabled: true

logging.level:
  org:
    springframework:
      web: INFO
      security: INFO
  web: DEBUG
  root: INFO
  com.company_name.project_name.ms: DEBUG
  com.company_name.cloud.infra: DEBUG
  org.hibernate.SQL: DEBUG
  org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  servlet:
    context-path: /api/v1
  error:
    include-message: always
    include-binding-errors: always
  tomcat:
    threads:
      max: 200
      min-spare: 20
    connection-timeout: 20000

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  main:
    banner-mode: off
    lazy-initialization: true       # Delay bean creation until first use
    allow-bean-definition-overriding: false

  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      pool-name: HikariPool-nl-service
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

