server:
  port: 5000

spring:
  application:
    name: nl-api-gateway

  cloud:
    # Route definitions of the system
    gateway:
      # discovery.locator.enabled: true
      routes:
        - id: products
          # lb:// is used to direct Spring Cloud Gateway to use the client-side load balancer
          # to look up the destination in the discovery service.
          uri: lb://products
          predicates:
            - Path=/products/**

        - id: eureka-api
          uri: http://${app.eureka.host}:${app.eureka.port}
          predicates:
            - Path=/eureka/api/{segment}
          filters:
            - SetPath=/eureka/{segment}

        - id: eureka-web-start
          uri: http://${app.eureka.host}:${app.eureka.port}
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        - id: eureka-web-other
          uri: http://${app.eureka.host}:${app.eureka.port}
          predicates:
            - Path=/eureka/**

        - id: config-server
          uri: http://${app.config-server.host}:${app.config-server.port}
          predicates:
            - Path=/config/**
          filters:
            - RewritePath=/config/(?<segment>.*), /$\{segment}

        # Testing URLs
        - id: host_route_200
          uri: http://httpstat.us
          predicates:
            - Host=i.feel.lucky:8080
            - Path=/headerrouting/**
          filters:
            - SetPath=/200

        - id: host_route_418
          uri: http://httpstat.us
          predicates:
            - Host=im.a.teapot:8080
            - Path=/headerrouting/**
          filters:
            - SetPath=/418

        - id: host_route_501
          uri: http://httpstat.us
          predicates:
            - Path=/headerrouting/**
          filters:
            - SetPath=/501