server:
  port: 5300

spring:
  application:
    name: nl-order-service
    
  datasource:
    url: jdbc:mysql://localhost:3306/ordersdb
    username: adminuser
    password: StrongPassword123!
    driver-class-name: com.mysql.cj.jdbc.Driver
